language: r
# warnings_are_errors: true
sudo: required

# bioc_packages:
#   - GEOquery
#   - Biobase
#
# r_github_packages:
#   - Rexamine/stringi
#
# r_packages:
#   - covr
#
#
# after_success:
#   - Rscript -e 'covr::codecov()'

