language: r
# warnings_are_errors: true
sudo: required

bioc_packages:
  - GEOquery
  - Biobase

# r_packages:
#   - covr

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'