---
title: "Mann-Whitney Gene Expression analysis"
author: "Florent Chuffart"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Mann-Whitney Gene Expression analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

Loading the epimedtools library

```{r}
library(epimedtools)
```

Creating a new study.

```{r}
study = create_study()
```

The .CEL.gz files are stored into two directories the *ctrl* directory and the *kc* directory:

```{r}
kc_cel_filedir = "../inst/extdata/trscr_raw_kc"
ctrl_cel_filedir = "../inst/extdata/trscr_raw_ctrl"
study$cel_filedirs = c(kc_cel_filedir, ctrl_cel_filedir)
print(study$cel_filedirs)
```


The RMA normalized data matrix is extract using the **get_data** method.

```{r}
head(study$get_data())
```

The associated clinical data

```{r}
print(study$get_exp_grp())
```

The Mann-Whitney analysis on 10 first probes.

```{r}
# selecting intersting probes
probe_names = rownames(study$get_data())[1:10]
# subset dataset
ctrl_exp_grp_key = "orig"
case_exp_grp_key = "orig"
ctrl_factor_name = "trscr_raw_ctrl"
case_factor_name = "trscr_raw_kc"

mw_pval = study$do_mw_test(probe_names, ctrl_exp_grp_key, case_exp_grp_key, ctrl_factor_name, case_factor_name)

```
